disabled_rules:
  - type_body_length
  - identifier_name

excluded:
  - Pods
  - Vendor

indentation: tabs

line_length:
     warning: 160
     error: 1000

trailing_whitespace:
    severity: warning

opening_brace: warning

colon:
  severity: warning

comma: warning

operator_usage_whitespace: warning
operator_whitespace: warning

vertical_parameter_alignment: warning

type_name: warning

opt_in_rules:
  - operator_usage_whitespace
  - private_outlet
  - weak_delegate
  - private_action
  - trailing_closure
  - attributes
  - modifier_order
  - fallthrough
  - implicit_return

type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50
  excluded: iPhone
reporter: "xcode"

control_statement: warning

statement_position:
  severity: warning

implicit_return:
  severity: warning

modifier_order:
    preferredModifierOrder: [acl, override]

attributes:
    always_on_line_above:
    - "@NSManaged"
    - "@discardableResult"
    - "@available"
    - "@NSCopying"
    - "@UIApplicationMain"
    - "@objc"

switch_case_alignment:
  severity: warning

empty_enum_arguments: warning
fallthrough: warning

force_cast: warning
force_try: warning

unused_optional_binding:
  severity: warning

closure_parameter_position: warning
multiple_closures_with_trailing_closure: warning


# Always leave a space after //
custom_rules:
    comments_space:
        name: "Space After Comment"
        message: "There should be a space after //"
        regex: (^ *\/\/\w+)
        severity: warning
mark: warning

todo:
  severity: warning

weak_delegate: warning
